### ISSUE TITLE
Computed Fields / Properties

### ISSUE THREAD

**Issue by gsomoza** [zfcampus/zf-apigility-doctrine#157]
For some context here's a (simple) example to illustrate what I need to do: given a User entity that has a "first_name" and a "last_name" column, I want the API to return a "full_name" field in addition to those columns. 

The computation in my use-case is a bit more complicated than that and involves querying other tables among other things. And its business-logic that we don't want to expose (other than the result as a field).

This would be something that's easy to do with traditional db-connected or code-connected resources. So my reasoning is that since its quite a common use-case it should be relatively easy to do here as well... but I can't seem to find a good way around it without working directly with a custom hydrator.

Am I missing something? Is it currently possible to return custom computed fields / properties without having to use a custom hydrator?

If not possible: would you be interested in a PR that incorporates that functionality?

**Comment by TomHAnderson** [comment]
This is a good use case for an RPC where you would not use a resource to POST data where the complimentary GET is returning computed fields.  That is, the POST and GET do not return the same data.

You could use a Query Provider to add more fields to the queryBuilder but the resource doesn't expect anything but the resource defined entity so you'd need to custom code the resource event too.  Which leads back to a RPC request.  This article may be of help:  http://tomhanderson.blogspot.com/2014/10/using-two-paginators-to-process.html

I do not see a solution to add computed field to an otherwise entity centric resource.  Any PR you submit will be considered to be sure.

**Comment by gabrielsomoza** [comment]
Thanks for the info! I'll take a look.

I understand the architectural considerations you brought up but I'm sure I'm not the only one trying to do this. In my case I wouldn't mind if the output of a GET is different from what we expect in a POST (e.g. the "full_name" attribute would just be ignored). But maybe a good compromise would be to extend the concepts of HAL to include a _computed section in addition to _embedded for example. Do you see that as a possibility?

**Comment by TomHAnderson** [comment]
My impression is extensions like _computed is in line with the intention of HAL.  I'd like to hear @weierophinney opinion on extending HAL in a direction like this.  I don't see adding _computed into the HAL plugin as a possibility but I do think a use case like this would open the idea of plugins into the HAL plugin to handle additional HAL data.

**Comment by TomHAnderson** [comment]
@gabrielsomoza adding computed fields may be a good use of a query provider.

**Comment by gabrielsomoza** [comment]
Great, I look forward to the feedback and I'm ready to create a PR once if I get a green light. 

I went ahead and proposed the idea in the HAL-discuss group to see if it catches any attention: https://groups.google.com/forum/#!topic/hal-discuss/GZcJg2W5WGI

**Comment by Wilt** [comment]
I think you can easily achieve this by custom setting your hydrator and adding a getter `getFullName()`. For extraction I mostly use the ZF2 `ClassMethods` hydrator and this works very well for me.
You can just add getters for all you want to see in the result and omit getters for the stuff you do not want to render. So in your case you would add something like this inside your entity:

````
public function getFullName()
{
    return $this->firstName . ' ' . $this->lastName;
}

**Comment by gabrielsomoza** [comment]
Thanks for the suggestion @Wilt, that would definitely be a good way to approach it. 

I'm looking for a slightly more generic approach that won't require coupling the Entity's public interface with what's outputted by the API - because the Entity is also used for other purposes (e.g. an Admin section).

I'm also interested in finding a good way of representing that information in the JSON output in a way that API consumers would know its a field that does not need to be returned to the server when updating the resource.

**Comment by TomHAnderson** [comment]
@gabrielsomoza any updates to this issue?

**Comment by gabrielsomoza** [comment]
The HAL group wasn't interested in going out of scope with something like _computed or _readonly, and their main proposed solution was to separate read-only properties into a sub-resource, letting the application figure out whether they're writable or not using HTTP Options (i.e. the resource would return only GET). This is actually a sensible approach in my opinion because it uses current standards but its so intricate that I can't imagine a lot of people would adopt it. I may of course be wrong.

Other people were OK with what's probably everybody's current approach: have api consumers "try" to write computed properties to their servers by including them in write requests, but then have the server just ignore any properties that weren't writable without any warning whatsoever.

So I guess its still up to each individual implementation to write clients that know which properties can be writable and which not - there's currently no consensus on how to decouple that. This probably means that if we want to allow easy computed properties in this module then we'll have to stick to the second option: no indication of which properties are computed or not + relatively tight coupling (at least in this particular sense) with the API consumer. 

As far as this particular ticket is concerned, I haven't worked on any practical solution primarily because I've been simply focusing on other parts of the project. I'll definitely circle back though cause I'll have to deal with the issue sooner or later.

Hope this is the kind of update you were looking for. If you're really interested in getting this solved please let me know - it would be encouraging to know you'd back it up. And if you really don't need this solved at all in the short / medium term, or even if you're just skeptical for the time being, please feel free to close the ticket :)

**Comment by jeremiahsmall** [comment]
It's definitely a tough design issue. It's great that the community is really focusing on REST fundamentalism, and big thanks to @weierophinney (and others) for championing HAL. Personally, I thing JSON RPC is more practical for this very reason.

**Comment by Wilt** [comment]
I also embraced the http `OPTIONS` method to communicate to the client what methods are allowed. In my current implementation I took this a step further by adding actions to my self-href. This prevents the client from having to do a `OPTIONS` request before every single operation.
I hesitated between using as a key name `methods` or `actions`. Since `actions` is more generic I used the latter.

An example of how a `self` `href` renders:
```
"self": {
    "actions": {
        "read": "GET",
        "edit": "PATCH",
        "delete": "DELETE",
    },
    "href": "http://hostname/api/v1/resources/1"
}
```

On collections where for example `POST` is also allowed:
```
"self": {
    "actions": {
        "create": "POST",
    },
    "href": "http://hostname/api/v1/resources/1"
}
```

**Comment by smknstd** [comment]
+1

@gabrielsomoza  ̀_computed` field makes a lot of sens to me!

Anyway, I am trying to do it with a custom hydrator but I can't find anywhere how to config it with apigility-doctrine. Do you have any idea where I can find some information ?

**Comment by Wilt** [comment]
You can set your hydrators in `zf-hal` inside the key `renderer`. Check the documentation [here](https://github.com/zfcampus/zf-hal#key-renderer).

I can actually not think of any scenario where a key `_computed` is really needed.

**Comment by gabrielsomoza** [comment]
@Wilt how about the scenario I mentioned in the description of the issue?

I do agree this turned out to be out of scope, and I did take the discussion over to the form that you mentioned a few months ago. The thread has a similar name as this issue's title.

This ticket is here to see if we can find a more practical solution than just issuing a separate OPTIONS request before each POST to an endpoint, which is what the people at the hal-json community suggested.

**Comment by Wilt** [comment]
@gabrielsomoza Is the `_computed` key  really needed in the `first_name`, `last_name` and `full_name` example (if that was the example you meant)? I think you can suffice with the current structure. Clients don't discover your `API` on-the-fly. Sending a patch request with `full_name` will return something like:

    "title": "Bad Request",
    "status": 400,
    "detail": "Unrecognized field \"full_name\""

While sending a patch to "fist_name" and/or "last_name" will deliver a 200 response with the changed resource including a new "full_name" value. The client has the responsability to exchange the whole resource in cache with the new resource that was returned by the server, thus resulting in a new "full_name" in the view. That this field was `_computed` seems irrelevant to me.

**Comment by gabrielsomoza** [comment]
So how do clients know they should avoid sending "full_name"? I hope its clear that what I'm trying to avoid is:
* Clients getting 4xx responses whenever they try to PATCH/POST (write) something to the API.
* Client UI's offering an editable text-box when showing the full_name field.
* etc.

**Comment by Wilt** [comment]
API documentation I guess?

**Comment by gabrielsomoza** [comment]
And by the way (at the risk of stating the obvious) the reason why I'm trying to avoid that is that its not practical and just seems like a waste of requests. To me this seems like an issue that should be solved architecturally, not by client-side "trial and error".

**Comment by gabrielsomoza** [comment]
> API documentation I guess?
Then the client knows too much about the resource, which makes it almost impossible to build HAL clients without somehow injecting application-specific business logic into them, which in turn makes it almost impossible to build a generic HAL client with the ability to write back to a server. Let alone smart UIs that can interact with an API 100% through the HAL standard.

Side note: maybe that's why most PHP-based HAL clients are read-only? Thought of that just know, but I'm sure there are many other use-cases.

**Comment by gabrielsomoza** [comment]
But that's the discussion we had in HAL, and their solution was to query with OPTIONS first. Fair enough, I get their point. That takes me back to the reason this issue exists: maybe there's a solution that we can implement just here, in this repository, that not necessarily conforms to a standard like HAL but that solves the issue for the many people like me that are having it: pretty much anyone that wants to build a clean, application-agnostic client that is able to both read/write a HAL-based API.

**Comment by TomHAnderson** [comment]
I'm open to the idea of zf-apigility-doctrine supporting a _computed key as a subset of a record.  I can even see it on the top level of a collection next to _links to provide the collectionTotal https://github.com/zfcampus/zf-apigility-doctrine/blob/master/src/Server/Resource/DoctrineResource.php#L589 data.  I've been looking for a way to remove or disassociate that field a long time.

The problem I see is the HAL processor is where this data would be processed.  @gabrielsomoza if you'd like to start a wip-pr (work in progress) that starts us in that direction that could be the catalyst we need.

**Comment by gabrielsomoza** [comment]
Awesome, I'll get that wip-pr ready for you.

**Comment by TomHAnderson** [comment]
Here's the answer: http://blog.tomhanderson.com/2016/06/appending-data-to-hal-response-or-how.html

**Comment by gsomoza** [comment]
Yeah, ended up doing that too. Since `_computed` is not a standard yet I think it makes sense to leave this up entirely to the user.
