### ISSUE TITLE
Enable fetchAll route params criteria

### ISSUE THREAD

**Issue by thomasvargiu** [zfcampus/zf-apigility-doctrine#187]
I should expect route ```/test/artist/:artist_id/album``` return a collection of ```Album``` where ```Album.artist``` == ```:artist_id``` and not the whole collection of ```Album```.
There is some reason why it's like that?
Can we apply the same criteria like in ```findEntity()``` method?

**Comment by thomasvargiu** [comment]
To do that, I need to edit ```ZF\Apigility\Doctrine\Server\Query\Provider\AbstractQueryProvider``` and ```ZF\Apigility\Doctrine\Server\Query\Provider\QueryProviderInterface```, providing a method which return a ```QueryBuilder``` for collection total, which possibly cause a BC break for who extended ```DefaultOrm``` and ```DefaultOrm``` overriding the ```getCollectionTotal()``` method.
Can we implement it in 1.1.0 version?

**Comment by TomHAnderson** [comment]
If your goal is to find albums then /api/album?artist=1 makes more logical sense.  Can you provide a better argument that complicating the route to try to represent relationships through routes is better than a single entity per endpoint?

**Comment by thomasvargiu** [comment]
Sure. I prefer a single endpoint for entity. But if you allow routing like ```/test/album/:album_id/artist/:artist_id``` so you should enable route for the relation collection. Or remove this functionality. Just my opinion.

**Comment by TomHAnderson** [comment]
Your latest example is aberrated.  I dislike the association that if one works and one doesn't then both should be removed.  It's splitting the baby.

How about a route pre-processor which would take routes like /artist/id/collection and rewrite them to proper /collection?artist=id?

**Comment by thomasvargiu** [comment]
Yeah, it could be a good solution. But I don't know if provide it automatically or let the user to chose to configure it. Maybe both.

**Comment by TomHAnderson** [comment]
I hope I didn't come across too dramatic.  The idea of subroutes has always been distasteful to me.  

I think combined with zf-doctrine-querybuilder, maybe, a route preparser could translate a subroute into a simple route.  It would take a translation burden off the base zf-apigility-doctrine library if routes were all simple.  To me subroutes are an infinite problem because someone will always want to add another sub.  But a route translator would allow for any sort of routing of subkeys back to a simple endpoint.  

I hope you'll find someone to take the lead on this.  I'm afraid I can't step forward for it.
