### ISSUE TITLE
ManyToMany cascade persist - The identifier id is missing

### ISSUE THREAD

**Issue by fabiopaiva** [zfcampus/zf-apigility-doctrine#218]
Can i persist a manyToMany in cascade?

I have the relation Person#Address as ManyToMany

    /**
     * @ORM\ManyToMany(targetEntity="Address, cascade={"persist","remove"}, orphanRemoval=true)
     */
    protected $address;

i tried to create this data:

    {
        "name":"Fábio",
        "address": [
            {
                "default": true,
                "street" : "test street"
            }
        ]
    }

i got this error:

`The identifier id is missing for a query of Namespace\\\\Entity\\\\Address`

But i don't have a id, i need to persist cascade

Any Help

**Comment by JuEger** [comment]
If you didn't find a solution yet (and if anyone else also has this issue). I also stumbled across this challenge (in fact took me 1 day because I was still using 1.0.1 (due to some minor issues i had with >=1.0.2))

In 1.0.2+ ZF\Apigility\Doctrine\Server\Event\Listener\CollectionListener was added, which allows to persist manyToMany Relations correctly. You just have to add the listener to the Resource configuration.

But there is still a limitation when using the CollectionListener: It's not possible to persist ManyToMany Relational Entities which are within a OneToOne or ManyToOne relation.
e.G.
```json
{
  "basket": {
    "total": 100,
    "currency": "USD",
    "item": [
      {
        "name": "My fancy Item",
        "quantity": 5,
        "unitPrice": 20
      }
    ]
  }
}
```
