### ISSUE TITLE
Fatal Error in Doctrine Connected Service

### ISSUE THREAD

**Issue by humphrey09** [zfcampus/zf-apigility-doctrine#244]
This is rather a question than an issue/bug: 

I have set up my project with the Apigility 1.3.2 skeleton and added the appropriate dependencies (Phpro\DoctrineHydrationModule, ZF\Apigility\Doctrine\Server in module config; ZF\Apigility\Admin, ZF\Apigility\Doctrine\Admin  in dev config).

I created a Doctrine Connected Service for a small entity (one id and one plain text field; no associations) within the UI, but as soon as I am trying request the entity via the generated API, I get the error message:

`Fatal error: Declaration of ZF\Apigility\Doctrine\Server\Resource\DoctrineResource::setHydrator() must be compatible with Zend\Hydrator\HydratorAwareInterface::setHydrator(Zend\Hydrator\HydratorInterface $hydrator) in C:\Users\<Username>\workspace\zf-apigility-skeleton-1.3.2\vendor\zfcampus\zf-apigility-doctrine\src\Server\Resource\DoctrineResource.php on line 41`

I tried the following Apigility Doctrine module versions:

`"zfcampus/zf-apigility-doctrine": "1.1.0"`
and the latest
`"zfcampus/zf-apigility-doctrine": "^2.0"`
(i.e. 2.0.1 via composer).
Both create the same error message as seen above.

I tried setting up a usual REST-Service (non Doctrine-connected) and it is being served properly. So there must be something wrong or missing in my Apigility Doctrine module config. Or I am missing something else (which I cannot see at the moment) as I am quite new to Apigility. I am really stuck here. 

Could you please give me hint?

**Comment by NewtonsNerds** [comment]
Note: this is a temporary solution before this module gets updated.

The latest [Zend\Hydrator](https://github.com/zendframework/zend-hydrator) is no longer compatible with this module. A workaround would be downgrade your Zend Framework to 2.5

In composer.json, change the version to:
`"zendframework/zendframework" : "2.5",`

Then you are good to go. I had the same issue when I reached to this article. Not just this, the recent upgrade of ZF2 modules such as [Zend\Cache](https://github.com/zendframework/zend-cache) has been breaking our code. Now it's breaking the official module without any notice during update, which is sad really. Because there is no version leap between 2.5 and 2.5.3 so the developer wouldn't expect the broken backward compatibility.

Cheers,
Siwei

**Comment by TomHAnderson** [comment]
Until I can get DoctrineModule up to speed with zend-hydrator you may find a composer.json at https://apiskeletons.com for Doctrine in Apigility.

**Comment by TomHAnderson** [comment]
For more information see https://github.com/doctrine/DoctrineModule/issues/546

**Comment by humphrey09** [comment]
Thank you very much for your help and your suggestions!

The workaround (until the issue is finally resolved) based on your suggestions, downgrading to 

`"zendframework/zendframework": "2.5.1",`
(did not want to install Apache `ext-ldap` as required in ZF 2.5) and due some other dependencies also
`"zfcampus/zf-apigility-admin": "1.3.3",`

did it for me. 

Thank you for your quick help!

**Comment by clemf** [comment]
@TomHAnderson Why is the composer.json on your site behind a paywall?

**Comment by TomHAnderson** [comment]
Because I created it.  How much must one person give of themselves for free in order be accepted?  If you want individual help I can bill you hourly instead.

**Comment by TomHAnderson** [comment]
@clemf this is not the appropriate forum for you question.  The email links at https://apiskeletons.com work perfectly well.  I'm going to delete your post on this closed thread.

**Comment by jonrwads** [comment]
I know this is closed, I ran into the same error today.  Has there been any update on this?  I see there is a pending merge request but it appears as if it wasn't merged.  Is there a time frame for this?
