### ISSUE TITLE
Error saving field

### ISSUE THREAD

**Issue by SilverioMiranda** [zfcampus/zf-apigility-doctrine#247]
If i tryy add more than one doctrine table at once :

I get this error:
![image](https://cloud.githubusercontent.com/assets/1939153/13558158/23c12300-e3dc-11e5-84e7-500852a981d3.png)

Response of input-filter PUT :

`{"type":"http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html","title":"Not Found","status":404,"detail"
:"The controller specified does not exist"}`

Then if i try to add again some tables are ignored in this screen :

![image](https://cloud.githubusercontent.com/assets/1939153/13558178/adf2e306-e3dc-11e5-8e4a-df7bb08c784c.png)

What details i need to add here?

**Comment by TomHAnderson** [comment]
This is a problem with https://github.com/zfcampus/zf-apigility-admin-ui

The problem is because Apigility does code generation a race condition exists when multiple entities are submitted at once.  You may work around this issue by running the built in PHP server from the command line PHP because it is single threaded and will not accept multiple calls to modify the same files at the same time.

@jguittard I think I mentioned this once.  Can you chip in with what you know?

**Comment by TomHAnderson** [comment]
@jguittard We need a check all box once checking more than one works.
