### ISSUE TITLE
Apply Criteria based on route params in fetchAll

### ISSUE THREAD

**Issue by fabioginzel** [zfcampus/zf-apigility-doctrine#248]
if i call /entity/entity_id/xxx
i think entity xxx filtered by entity_id

**Comment by TomHAnderson** [comment]
Are you asking about multikeys?
https://github.com/zfcampus/zf-apigility-doctrine/blob/master/src/Server/Resource/DoctrineResource.php#L707

**Comment by fabioginzel** [comment]
No, i'm asking about fetch all entities by route param

**Comment by fabioginzel** [comment]
@TomHAnderson please merge my pull request

**Comment by TomHAnderson** [comment]
The idea you have put forward was retired in Zend Framework 1.  It had it's time and that time has passed.  In order to create better filters I created zf-doctrine-querybuilder.  I am keen to remove the multi-key already in zf-apigility-doctrine.  Trying to artificially build urls for data which should be filtered via get paramters.  Perhaps a re-router which can take url parameters and turn them into query parameters for the get string which is then passed to zf-apigility-doctrine.  

What you're proposing I do not see as beneficial to the project.  So it is your job to create a persuasive enough argument that your patch may be applied.

**Comment by fabioginzel** [comment]
@TomHAnderson 

I think that my patch should be applied , because the delete, fetch , patch and update methods already use the route parameters to filter entities , or stop using or fetchAll should also use.

**Comment by fabioginzel** [comment]
@TomHAnderson 
What do you think ?

**Comment by TomHAnderson** [comment]
Filtering of entities in a fetchAll belongs to the GET parameters.  https://github.com/API-Skeletons/zf-doctrine-querybuilder does this very well.  Route parameters in other methods are enabled because those other methods are intended to act upon one entity.  So, GET /entity/1 is for entity id 1.  GET /entity/filter/some/other/filter/ makes no sense.  They are both GET with route parameters per your argument.  So you're trying to add route parameters to something which already implements route parameters.  

This will not be merged.
